"""empty message

Revision ID: 1c28d5831b2b
Revises: bf70dea13666
Create Date: 2020-04-30 15:37:38.479575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c28d5831b2b'
down_revision = 'bf70dea13666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('capital', sa.String(length=64), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_capital'), 'country', ['capital'], unique=False)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_capital'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
